version: '3.8'

services:
  s3:
    image: minio/minio:latest
    command: server /data --console-address ":43719"
    ports:
      - "9000:9000"
      - "43719:43719"
    volumes:
      - ./data:/data
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=locallocal
      - MINIO_ROOT_USER=local
      - MINIO_ROOT_PASSWORD=locallocal
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://s3:9000
  glue:
    container_name: glue
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      DISABLE_SSL: 'true'
      JOB_NAME: test
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: locallocal
      AWS_REGION: us-east-1
      GLUE_JOB_MODE: development
    volumes:
      - .:/home/glue_user/workspace:rw
    network_mode: "host"
    links:
      - s3